apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lighthouse-auth-internal-ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: internal.172.21.0.3.xip.io
    http:
      paths:
      - path: /internal
        backend:
          serviceName: lighthouse-auth
          servicePort: 8080
